_tc = [
    (
        [(0, 0, 0)],
        (1, 0, 0),
    ),
    (
        [
            (2, 0, 0),
            (-1, 0, 0),
        ],
        (0, 0, 0),
    ),
    (
        [
            (100, 0, 0),
            (0, 100, 0),
            (0, 0, 100),
            (100, 100, 100),
        ],
        (55.5, 66.6, 77.7),
    ),
    (
        [
            (-96.76111578534301, 16.74073513068501, -25.42560579386131),
            (94.48805673916527, 2.5210738380925193, 46.38707372329512),
            (85.16902143588126, -96.76964404174211, 84.30420095088618),
            (17.04971983379788, 55.23739526025827, 15.509333245779857),
            (-97.99964339622684, -62.99543656295681, -66.22982013426014),
            (-8.03887315135654, -12.599210689119772, 0.08970148500900166),
            (96.45178703152203, 4.2403316193437774, -48.21032175566478),
            (-28.237910473867018, -59.18130474838272, -62.39925890243669),
            (16.022762282064008, -31.039548113295183, 90.48267505805762),
            (-40.952370104202316, 96.77143020283646, 67.45418964900239),
        ],
        (-91.21056199339668, -39.316319928854114, -29.884097500120305),
    ),
]

from Rhino.Geometry import Point3d

tc_c = [
    [Point3d(*_pt) for _pt in _pts] for _pts in [[_j for _j in _i[0]] for _i in _tc]
]


tc_p = [Point3d(*_pt) for _pt in [map(float, [_j for _j in _i[1]]) for _i in _tc]]
