_tc = [
    (
        [
            (2, 0, 0),
            (-1, 0, 0),
            (0, 3, 0),
        ],
    ),
    (
        [
            (100, 0, 0),
            (0, 100, 0),
            (0, 0, 0),
            (100, 100, 0),
        ],
    ),
    (
        [
            (100, 0, 0),
            (10, 0, 0),
            (0, 100, 0),
            (0, 50, 0),
            (0, 0, 0),
            (100, 100, 0),
            (70, 100, 0),
            (30, 100, 0),
        ],
    ),
    (
        [
            (-96.76111578534301, 16.74073513068501, 0),
            (94.48805673916527, 2.5210738380925193, 0),
            (85.16902143588126, -96.76964404174211, 0),
            (17.04971983379788, 55.23739526025827, 0),
            (-97.99964339622684, -62.99543656295681, 0),
            (-8.03887315135654, -12.599210689119772, 0),
            (96.45178703152203, 4.2403316193437774, 0),
            (-28.237910473867018, -59.18130474838272, 0),
            (16.022762282064008, -31.039548113295183, 0),
            (-40.952370104202316, 96.77143020283646, 0),
        ],
    ),
]

from Rhino.Geometry import Point3d

tc_p = [
    [Point3d(*_pt) for _pt in _pts] for _pts in [[_j for _j in _i[0]] for _i in _tc]
]
